export { default as AppPage } from './AppPage.vue'
export { default as AppText } from './AppText.vue'
export { default as AppBtn } from './AppBtn.vue'
export { default as AppLinkBtn } from './AppLinkBtn.vue'
export { default as AppLoading } from './AppLoading.vue'
